import { ROLES } from "./roles";
import {
  SquaresFour,
  UsersThree,
  Compass,
  Buildings,
  Tag,
  CurrencyDollar,
  Bed,
  UserGear,
  Briefcase,
  CalendarCheck,
  EnvelopeSimple,
  Package,
  CreditCard,
  ShieldCheck,
  Lifebuoy,
} from "@phosphor-icons/react";
import MailboxView from "../components/views/MailboxView";
import CompanyPlanView from "../platformAdmin/CompanyPlanView";

const { SUPER_ADMIN, ADMIN, RM, SALE, GUIDE } = ROLES;

export const resources = {
  dashboard: {
    title: "Dashboard",
    icon: SquaresFour,
    page: "DashboardPage",
    roles: [SUPER_ADMIN, ADMIN, RM, SALE, GUIDE],
  },
  clients: {
    title: "Clients",
    singular: "Client",
    icon: UsersThree,
    endpoint: "/clients",
    roles: [ADMIN, RM, SALE],
    permissions: {
      view: [ADMIN, RM, SALE],
      create: [ADMIN, SALE],
      update: [ADMIN, SALE],
      delete: [ADMIN],
    },
    table: {
      searchable: true,
      filters: [
        {
          key: "status",
          label: "Status",
          type: "select",
          defaultValue: "",
          options: [
            { label: "All Statuses", value: "" },
            { label: "Active", value: "ACTIVE" },
            { label: "Inactive", value: "INACTIVE" },
          ],
        },
      ],
      actions: [
        { key: "view", label: "View & Details" },
        { key: "update", label: "Edit" },
      ],
    },
    fields: [
      {
        name: "firstName",
        label: "First Name",
        type: "text",
        required: true,
        showInTable: true,
      },
      {
        name: "lastName",
        label: "Last Name",
        type: "text",
        required: true,
        showInTable: true,
      },
      {
        name: "gender",
        label: "Gender",
        type: "select",
        required: true,
        options: [
          { label: "Male", value: "MALE" },
          { label: "Female", value: "FEMALE" },
        ],
        showInTable: true,
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        required: true,
        showInTable: true,
      },
      {
        name: "phone",
        label: "Phone",
        type: "tel",
        required: true,
        showInTable: true,
      },
      {
        name: "nationality",
        label: "Nationality",
        type: "text",
        showInTable: true,
      },
      {
        name: "preferredLanguage",
        label: "Preferred Language",
        type: "text",
        showInTable: true,
      },
      {
        name: "countryOfResidence",
        label: "Country of Residence",
        type: "text",
        showInTable: false,
      },
      {
        name: "notes",
        label: "Notes",
        type: "textarea",
        showInTable: false,
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        defaultValue: "ACTIVE",
        options: [
          { label: "Active", value: "ACTIVE" },
          { label: "Inactive", value: "INACTIVE" },
        ],
        showInTable: true,
        decorate: "status",
      },
    ],
  },
  safaris: {
    title: "Safaris",
    singular: "Safari",
    icon: Compass,
    endpoint: "/safari/company",
    roles: [ADMIN, SALE, RM, GUIDE],
    permissions: {
      view: [ADMIN, SALE, RM, GUIDE],
      create: [ADMIN, SALE],
      update: [ADMIN, SALE],
      delete: [ADMIN, SALE],
    },
    table: {
      searchable: true,
      filters: [
        {
          key: "status",
          label: "Safari Status",
          type: "select",
          defaultValue: "",
          options: [
            { label: "All Statuses", value: "" },
            { label: "Draft", value: "DRAFT" },
            { label: "Confirmed", value: "CONFIRMED" },
            { label: "Completed", value: "COMPLETED" },
            { label: "Cancelled", value: "CANCELLED" },
          ],
        },
      ],
      actions: [
        { key: "view", label: "View Days & Details" },
      ],
    },
    fields: [
      {
        name: "referenceNumber",
        label: "Reference",
        type: "text",
        editable: false,
        showInTable: true,
      },
      {
        name: "clientName",
        label: "Client",
        type: "text",
        editable: false,
        showInTable: true,
      },
      {
        name: "clientId",
        label: "Select Client",
        type: "select",
        required: true,
        showInTable: false,
        dynamicOptions: "clients",
      },
      {
        name: "salesPersonName",
        label: "Sales Person",
        type: "text",
        editable: false,
        showInTable: true,
      },
      {
        name: "startDate",
        label: "Start Date",
        type: "date",
        required: true,
        showInTable: true,
      },
      {
        name: "endDate",
        label: "End Date",
        type: "date",
        required: true,
        showInTable: true,
      },
      {
        name: "numberOfPassengers",
        label: "Passengers",
        type: "number",
        required: true,
        showInTable: true,
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        editable: false,
        options: [
          { label: "Draft", value: "DRAFT" },
          { label: "Confirmed", value: "CONFIRMED" },
          { label: "Completed", value: "COMPLETED" },
          { label: "Cancelled", value: "CANCELLED" },
        ],
        showInTable: true,
        decorate: "safariStatus",
      },
      {
        name: "notes",
        label: "Notes",
        type: "textarea",
        showInTable: false,
      },
    ],
  },
  properties: {
    title: "Properties",
    singular: "Property",
    icon: Buildings,
    endpoint: "/properties",
    roles: [SUPER_ADMIN, ADMIN, RM],
    permissions: {
      view: [SUPER_ADMIN, ADMIN, RM],
      create: [SUPER_ADMIN, ADMIN, RM],
      update: [SUPER_ADMIN, ADMIN, RM],
      delete: [SUPER_ADMIN, ADMIN],
      verify: [SUPER_ADMIN, ADMIN, RM],
    },
    table: {
      searchable: true,
      filters: [
        {
          key: "status",
          label: "Verification",
          type: "select",
          defaultValue: "",
          options: [
            { label: "All", value: "" },
            { label: "Pending", value: "PENDING" },
            { label: "Verified", value: "VERIFIED" },
          ],
        },
      ],
      actions: [
        { key: "view", label: "View" },
        { key: "update", label: "Edit" },
      ],
    },
    fields: [
      {
        name: "name",
        label: "Property Name",
        type: "text",
        required: true,
        showInTable: true,
      },
      {
        name: "location",
        label: "Location",
        type: "text",
        required: true,
        showInTable: true,
      },
      {
        name: "region",
        label: "Region",
        type: "text",
        showInTable: true,
      },
      {
        name: "country",
        label: "Country",
        type: "text",
        required: true,
        showInTable: true,
      },
      {
        name: "categoryId",
        label: "Category",
        type: "select",
        required: true,
        showInTable: false,
        dynamicOptions: "property-categories",
      },
      {
        name: "priceId",
        label: "Price Tier",
        type: "select",
        required: true,
        showInTable: false,
        dynamicOptions: "price-tiers",
      },
      {
        name: "categoryName",
        label: "Category",
        type: "text",
        editable: false,
        showInTable: true,
      },
      {
        name: "priceTierName",
        label: "Price Tier",
        type: "text",
        editable: false,
        showInTable: true,
      },
      {
        name: "contactName",
        label: "Contact Person",
        type: "text",
        showInTable: true,
      },
      {
        name: "contactEmail",
        label: "Contact Email",
        type: "email",
        showInTable: false,
      },
      {
        name: "contactPhone",
        label: "Contact Phone",
        type: "tel",
        showInTable: false,
      },
      {
        name: "website",
        label: "Website",
        type: "text",
        showInTable: false,
      },
      {
        name: "verificationStatus",
        label: "Verification",
        type: "text",
        editable: false,
        showInTable: true,
        decorate: "verificationStatus",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        showInTable: false,
      },
    ],
  },
  "accommodation-bookings": {
    title: "Accommodation Bookings",
    singular: "Booking",
    icon: CalendarCheck,
    endpoint: "/accommodation-bookings",
    roles: [SUPER_ADMIN, ADMIN, RM, SALE],
    permissions: {
      view: [SUPER_ADMIN, ADMIN, RM, SALE],
      create: [ADMIN, RM],
      update: [ADMIN, RM],
      delete: [ADMIN],
    },
    table: {
      searchable: true,
      filters: [
        {
          key: "status",
          label: "Status",
          type: "select",
          defaultValue: "",
          options: [
            { label: "All Statuses", value: "" },
            { label: "Draft", value: "DRAFT" },
            { label: "Provisional", value: "PROVISIONAL" },
            { label: "Confirmed", value: "CONFIRMED" },
            { label: "Cancelled", value: "CANCELLED" },
          ],
        },
      ],
      actions: [
        { key: "view", label: "View Details" },
      ],
    },
    fields: [
      {
        name: "referenceNumber",
        label: "Booking Ref",
        type: "text",
        editable: false,
        showInTable: true,
      },
      {
        name: "propertyName",
        label: "Lodge / Property",
        type: "text",
        editable: false,
        showInTable: true,
      },
      {
        name: "destination",
        label: "Destination",
        type: "text",
        editable: false,
        showInTable: true,
      },
      {
        name: "safariReference",
        label: "Safari Reference",
        type: "text",
        editable: false,
        showInTable: true,
      },
      {
        name: "checkIn",
        label: "Check-in",
        type: "date",
        required: true,
        showInTable: true,
      },
      {
        name: "checkOut",
        label: "Check-out",
        type: "date",
        required: true,
        showInTable: true,
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        editable: false,
        showInTable: true,
        decorate: "status",
      },
      {
        name: "confirmationNumber",
        label: "Confirmation #",
        type: "text",
        showInTable: true,
      },
      {
        name: "reservationManagerName",
        label: "Assigned Staff",
        type: "text",
        editable: false,
        showInTable: true,
      },
      {
        name: "notes",
        label: "Notes & Requests",
        type: "textarea",
        showInTable: false,
      },
    ],
  },
  mailbox: {
    title: "Mailbox & Invoices",
    singular: "Mailbox",
    icon: EnvelopeSimple,
    page: MailboxView,
    roles: [SUPER_ADMIN, ADMIN, RM, SALE],
  },
  "property-categories": {
    title: "Categories",
    singular: "Category",
    icon: Tag,
    endpoint: "/property-category",
    roles: [ADMIN, RM],
    permissions: {
      view: [ADMIN, RM],
      create: [ADMIN, RM],
      update: [ADMIN, RM],
      delete: [ADMIN, RM],
    },
    table: {
      searchable: false,
      actions: [
        { key: "view", label: "View" },
        { key: "update", label: "Edit" },
        { key: "delete", label: "Delete" },
      ],
    },
    fields: [
      {
        name: "name",
        label: "Category Name",
        type: "text",
        required: true,
        showInTable: true,
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        showInTable: true,
      },
    ],
  },
  "price-tiers": {
    title: "Price Tiers",
    singular: "Price Tier",
    icon: CurrencyDollar,
    endpoint: "/price-tier",
    roles: [ADMIN, RM],
    permissions: {
      view: [ADMIN, RM],
      create: [ADMIN, RM],
      update: [ADMIN, RM],
      delete: [ADMIN, RM],
    },
    table: {
      searchable: false,
      actions: [
        { key: "view", label: "View" },
        { key: "update", label: "Edit" },
        { key: "delete", label: "Delete" },
      ],
    },
    fields: [
      {
        name: "name",
        label: "Tier Name",
        type: "text",
        required: true,
        showInTable: true,
      },
      {
        name: "currency",
        label: "Currency",
        type: "text",
        defaultValue: "USD",
        required: true,
        showInTable: true,
      },
      {
        name: "minPrice",
        label: "Min Price",
        type: "number",
        required: true,
        showInTable: true,
      },
      {
        name: "maxPrice",
        label: "Max Price",
        type: "number",
        required: true,
        showInTable: true,
      },
    ],
  },
  "room-types": {
    title: "Room Types",
    singular: "Room Type",
    icon: Bed,
    endpoint: "/api/v1/room-types",
    roles: [ADMIN, RM, SALE],
    permissions: {
      view: [ADMIN, RM, SALE],
      create: [ADMIN, SALE],
      update: [ADMIN, SALE],
      delete: [ADMIN],
    },
    table: {
      searchable: false,
      actions: [
        { key: "update", label: "Edit" },
        { key: "delete", label: "Delete" },
      ],
    },
    fields: [
      {
        name: "name",
        label: "Room Type Name",
        type: "text",
        required: true,
        showInTable: true,
      },
    ],
  },
  users: {
    title: "Users",
    singular: "User",
    icon: UserGear,
    endpoint: "/api/users/get-users",
    createEndpoint: "/api/users/create_user",
    updateEndpoint: "/api/users/user",
    roles: [SUPER_ADMIN, ADMIN],
    permissions: {
      view: [SUPER_ADMIN, ADMIN],
      create: [SUPER_ADMIN, ADMIN],
      update: [SUPER_ADMIN, ADMIN],
    },
    table: {
      searchable: true,
      actions: [
        { key: "view", label: "View Details" },
        { key: "update", label: "Edit" },
      ],
    },
    fields: [
      {
        name: "companyName",
        label: "Company Name (optional if your company)",
        type: "text",
        required: false,
        showInTable: true,
      },
      {
        name: "firstName",
        label: "First Name",
        type: "text",
        required: true,
        showInTable: true,
      },
      {
        name: "lastName",
        label: "Last Name",
        type: "text",
        required: true,
        showInTable: true,
      },
      {
        name: "gender",
        label: "Gender",
        type: "select",
        required: false,
        options: [
          { label: "Male", value: "MALE" },
          { label: "Female", value: "FEMALE" },
        ],
        showInTable: true,
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        required: true,
        showInTable: true,
      },
      {
        name: "phone",
        label: "Phone",
        type: "tel",
        showInTable: true,
      },
      {
        name: "roleName",
        label: "Role",
        type: "select",
        required: true,
        showInTable: false,
        options: [
          { label: "Admin", value: "ADMIN" },
          { label: "Sales Person", value: "SALES_PERSON" },
          { label: "Reservation Manager", value: "RESERVATION_MANAGER" },
          { label: "Guide", value: "GUIDE" },
        ],
      },
      {
        name: "password",
        label: "Password",
        type: "password",
        required: true,
        showInTable: false,
      },
      {
        name: "role",
        label: "Role",
        type: "text",
        editable: false,
        showInTable: true,
      },
      {
        name: "status",
        label: "Status",
        type: "text",
        editable: false,
        showInTable: true,
        decorate: "status",
      },
    ],
  },
  companies: {
    title: "Companies",
    singular: "Company",
    icon: Briefcase,
    endpoint: "/api/company/companies",
    createEndpoint: "/api/company/create",
    roles: [SUPER_ADMIN],
    permissions: {
      view: [SUPER_ADMIN],
      create: [SUPER_ADMIN],
      update: [SUPER_ADMIN],
    },
    table: {
      searchable: false,
      actions: [
        { key: "view", label: "View" },
      ],
    },
    fields: [
      {
        name: "name",
        label: "Company Name",
        type: "text",
        required: true,
        showInTable: true,
        placeholder: "e.g., Serengeti Wonders Safari Ltd",
      },
      {
        name: "email",
        label: "Company Email",
        type: "email",
        required: true,
        showInTable: true,
        placeholder: "e.g., info@serengetiwonders.com",
      },
      {
        name: "phone",
        label: "Phone Number",
        type: "tel",
        required: true,
        showInTable: true,
        placeholder: "e.g., +255 754 123 456",
      },
      {
        name: "country",
        label: "Country",
        type: "text",
        required: true,
        defaultValue: "Tanzania",
        showInTable: true,
        placeholder: "e.g., Tanzania, Kenya, Uganda",
      },
      {
        name: "timezone",
        label: "Timezone",
        type: "text",
        defaultValue: "Africa/Dar_es_Salaam",
        showInTable: false,
        placeholder: "e.g., Africa/Dar_es_Salaam",
      },
      {
        name: "subscription_plan",
        label: "Subscription Plan",
        type: "select",
        required: true,
        showInTable: false,
        dynamicOptions: "subscription_plan",
      },
      {
        name: "subscriptionPlanName",
        label: "Assigned Plan",
        type: "text",
        editable: false,
        showInTable: true,
        decorate: "badge",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        defaultValue: "ACTIVE",
        options: [
          { label: "Active", value: "ACTIVE" },
          { label: "Inactive", value: "INACTIVE" },
          { label: "Cancelled", value: "CANCELLED" },
          { label: "Expired", value: "EXPIRED" },
        ],
        showInTable: true,
        decorate: "status",
      },
    ],
  },
  "subscription-plans": {
    title: "Subscription Plans",
    singular: "Subscription Plan",
    icon: Package,
    endpoint: "/api/subscription-plans",
    createEndpoint: "/api/subscription-plans/create",
    roles: [SUPER_ADMIN],
    permissions: {
      view: [SUPER_ADMIN],
      create: [SUPER_ADMIN],
      update: [SUPER_ADMIN],
    },
    table: {
      searchable: false,
      actions: [
        { key: "view", label: "View" },
      ],
    },
    fields: [
      {
        name: "name",
        label: "Plan Name",
        type: "text",
        required: true,
        showInTable: true,
        placeholder: "e.g., Starter Plan, Professional Plan",
      },
      {
        name: "price",
        label: "Monthly Price",
        type: "number",
        required: true,
        showInTable: true,
        placeholder: "e.g., 99.00",
      },
      {
        name: "currency",
        label: "Currency",
        type: "select",
        required: true,
        defaultValue: "USD",
        options: [
          { label: "USD ($)", value: "USD" },
          { label: "EUR (€)", value: "EUR" },
          { label: "TZS (TSh)", value: "TZS" },
        ],
        showInTable: true,
      },
      {
        name: "maxUsers",
        label: "Max Users Limit",
        type: "number",
        required: true,
        showInTable: true,
        placeholder: "e.g., 5, 20, 100",
      },
      {
        name: "status",
        label: "Plan Status",
        type: "select",
        required: true,
        defaultValue: "ACTIVE",
        options: [
          { label: "Active", value: "ACTIVE" },
          { label: "Inactive", value: "INACTIVE" },
        ],
        showInTable: true,
        decorate: "status",
      },
    ],
  },
  "company-plan": {
    title: "Company Subscription",
    singular: "Subscription",
    icon: CreditCard,
    roles: [ADMIN],
    page: CompanyPlanView,
  },
  "audit-logs": {
    title: "Audit Logs",
    singular: "Audit Log",
    icon: ShieldCheck,
    endpoint: "/api/v1/audit-logs",
    roles: [SUPER_ADMIN, ADMIN],
    permissions: {
      view: [SUPER_ADMIN, ADMIN],
    },
    table: {
      searchable: true,
      actions: [
        { key: "view", label: "View Details" },
      ],
    },
    fields: [
      {
        name: "action",
        label: "Action",
        type: "text",
        editable: false,
        showInTable: true,
      },
      {
        name: "entityType",
        label: "Entity",
        type: "text",
        editable: false,
        showInTable: true,
      },
      {
        name: "userEmail",
        label: "Actor",
        type: "text",
        editable: false,
        showInTable: true,
      },
      {
        name: "ipAddress",
        label: "IP Address",
        type: "text",
        editable: false,
        showInTable: true,
      },
      {
        name: "createdAt",
        label: "Date & Time",
        type: "text",
        editable: false,
        showInTable: true,
      },
      {
        name: "oldValues",
        label: "Previous State (JSON)",
        type: "textarea",
        editable: false,
        showInTable: false,
      },
      {
        name: "newValues",
        label: "New State (JSON)",
        type: "textarea",
        editable: false,
        showInTable: false,
      },
    ],
  },
  "support-tickets": {
    title: "Support Tickets",
    singular: "Support Ticket",
    icon: Lifebuoy,
    endpoint: "/api/v1/support-tickets",
    updateEndpoint: "/api/v1/support-tickets",
    roles: [SUPER_ADMIN, ADMIN, RM, SALE],
    permissions: {
      view: [SUPER_ADMIN, ADMIN, RM, SALE],
      create: [SUPER_ADMIN, ADMIN, RM, SALE],
      update: [SUPER_ADMIN, ADMIN, RM],
    },
    table: {
      searchable: true,
      filters: [
        {
          key: "status",
          label: "Ticket Status",
          type: "select",
          defaultValue: "",
          options: [
            { label: "All Statuses", value: "" },
            { label: "Open", value: "OPEN" },
            { label: "In Progress", value: "IN_PROGRESS" },
            { label: "Resolved", value: "RESOLVED" },
            { label: "Closed", value: "CLOSED" },
          ],
        },
      ],
      actions: [
        { key: "view", label: "View Details" },
        { key: "update", label: "Resolve / Edit" },
      ],
    },
    fields: [
      {
        name: "subject",
        label: "Subject",
        type: "text",
        required: true,
        showInTable: true,
      },
      {
        name: "category",
        label: "Category",
        type: "select",
        required: true,
        options: [
          { label: "Login Issue", value: "LOGIN_ISSUE" },
          { label: "Payment Issue", value: "PAYMENT_ISSUE" },
          { label: "Booking Issue", value: "BOOKING_ISSUE" },
          { label: "Account Issue", value: "ACCOUNT_ISSUE" },
          { label: "Technical", value: "TECHNICAL" },
          { label: "Other", value: "OTHER" },
        ],
        showInTable: true,
      },
      {
        name: "priority",
        label: "Priority",
        type: "select",
        required: true,
        options: [
          { label: "Low", value: "LOW" },
          { label: "Medium", value: "MEDIUM" },
          { label: "High", value: "HIGH" },
          { label: "Urgent", value: "URGENT" },
        ],
        showInTable: true,
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        defaultValue: "OPEN",
        options: [
          { label: "Open", value: "OPEN" },
          { label: "In Progress", value: "IN_PROGRESS" },
          { label: "Resolved", value: "RESOLVED" },
          { label: "Closed", value: "CLOSED" },
        ],
        showInTable: true,
        decorate: "status",
      },
      {
        name: "raisedByName",
        label: "Raised By",
        type: "text",
        editable: false,
        showInTable: true,
      },
      {
        name: "assignedToName",
        label: "Assigned To",
        type: "text",
        editable: false,
        showInTable: true,
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        required: true,
        showInTable: false,
      },
      {
        name: "resolutionNotes",
        label: "Resolution Notes",
        type: "textarea",
        showInTable: false,
      },
    ],
  },
};
